import type { OrderObservation } from '@orderrescue/domain';

/**
 * The seam between OrderRescue and whatever actually places the order.
 *
 * The Binance Spot Testnet implementation lives in spot.ts. An Agent OS
 * execution adapter would implement this same interface — but only once its
 * real tool schema has been inspected and it can be shown to carry a stable
 * client-supplied identifier through placement and back out through status.
 * See docs/integration-gate.md.
 */
export interface ExecutionAdapter {
  readonly venue: string;
  readonly environment: 'TESTNET' | 'MAINNET';
  capabilities(): Promise<CapabilityReport>;
  placeOrder(request: PlaceOrderRequest): Promise<SubmissionOutcome>;
  getOrderByClientOrderId(symbol: string, clientOrderId: string): Promise<StatusOutcome>;
  cancelOrderByClientOrderId(symbol: string, clientOrderId: string): Promise<StatusOutcome>;
  getAccountBalances(assets: string[]): Promise<AccountObservation>;
}

export interface PlaceOrderRequest {
  symbol: string;
  side: 'BUY' | 'SELL';
  orderType: 'MARKET' | 'LIMIT';
  quantity: string | null;
  quoteQuantity: string | null;
  limitPrice: string | null;
  timeInForce: string | null;
  /** The correlation key. Chosen before dispatch; never generated by the venue. */
  clientOrderId: string;
}

/**
 * Three outcomes, and the third one is the whole point.
 *
 * ACKNOWLEDGED — the venue told us what it did.
 * REJECTED     — the venue told us it did nothing, and identified itself while
 *                saying so. Only a parsed venue error envelope earns this.
 * AMBIGUOUS    — we do not know. Timeouts, 5xx, unreadable bodies, rate limits,
 *                and Binance's own -1007 all land here. Never inferred as failure.
 */
export type SubmissionOutcome =
  | { kind: 'ACKNOWLEDGED'; observation: OrderObservation; requestDigest: string; responseDigest: string }
  | { kind: 'REJECTED'; venueCode: number; reason: string; requestDigest: string; responseDigest: string }
  | { kind: 'AMBIGUOUS'; reason: string; detail: string; requestDigest: string };

export type StatusOutcome =
  | { kind: 'OBSERVED'; observation: OrderObservation; responseDigest: string }
  | { kind: 'ABSENT'; venueCode: number; responseDigest: string }
  | { kind: 'UNAVAILABLE'; reason: string; detail: string };

export interface AccountObservation {
  balances: Array<{ asset: string; free: string; locked: string }>;
  sourceTimestamp: string | null;
  responseDigest: string;
}

export interface CapabilityReport {
  reachable: boolean;
  authenticated: boolean;
  environment: 'TESTNET' | 'MAINNET';
  serverTimeSkewMs: number | null;
  /** True only when placement accepts, and status can query, a caller-chosen id. */
  supportsClientOrderIdCorrelation: boolean;
  symbolFilters: Record<string, SymbolFilters>;
  problems: string[];
}

export interface SymbolFilters {
  status: string;
  minNotional: string | null;
  maxNotional: string | null;
  stepSize: string | null;
  minQty: string | null;
  tickSize: string | null;
  baseAsset: string;
  quoteAsset: string;
}
